<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Summa.Fiscal.Worker-f6e3634c-9301-431a-9448-80d4faf20a0d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Summa.Fiscal.Application\Summa.Fiscal.Application.csproj" />
    <ProjectReference Include="..\Summa.Fiscal.Infrastructure\Summa.Fiscal.Infrastructure.csproj" />
    <ProjectReference Include="..\Summa.Fiscal.Persistence\Summa.Fiscal.Persistence.csproj" />
  </ItemGroup>
</Project>
